import type { Metadata } from "next";
import { Geist, Geist_Mono, Noto_Sans_KR } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// 사용자 지시(2026-08-21): Page 1 디자인 개편 시 tvn.cjenm.com을 레퍼런스로 확인한 결과,
// 그 사이트는 Noto Sans KR을 쓴다 — Geist는 라틴 문자만 지원해 한글은 웹폰트가 전혀 적용되지
// 않고 OS 기본 한글 글꼴(Windows는 맑은 고딕 등)로 조용히 대체되고 있었다(실측: 화면 대부분이
// 한글 텍스트인데 그동안 실제로는 한 번도 웹폰트가 한글에 적용된 적이 없었음). 한글 비중이
// 절대적인 이 서비스 특성상 Noto Sans KR을 본문 글꼴로 추가한다(Geist는 영문/숫자 혼용 구간을
// 위해 유지).
const notoSansKr = Noto_Sans_KR({
  variable: "--font-noto-sans-kr",
  subsets: ["latin"],
  weight: ["400", "500", "700"],
});

// 사용자 지시(2026-08-21, Page 1 매거진 개편): 메인 제목·섹션 헤더에 "옴니고딕 계열"을 요청했으나
// 옴니고딕(산돌)은 상용 라이선스 폰트라 next/font/google에도 없고 무료로 정당하게 쓸 수 없다 —
// 대신 국내 모던 UI에서 옴니고딕류의 대체재로 가장 널리 쓰이는 무료 오픈소스(OFL 라이선스)
// Pretendard를 헤더 전용 폰트로 추가한다(제목/큰 숫자에만 적용, 본문은 기존 Geist+Noto Sans KR
// 유지 — "제목은 임팩트 있게, 본문은 차분하게"라는 이번 지시와도 맞물림). 가변 폰트 파일 하나로
// 전체 굵기(45~920)를 커버해 next/font/local로 자체 호스팅.
const pretendard = localFont({
  src: "./fonts/PretendardVariable.woff2",
  variable: "--font-pretendard",
  weight: "45 920",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="ko"
      className={`${geistSans.variable} ${geistMono.variable} ${notoSansKr.variable} ${pretendard.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
