import type { Metadata } from "next";
import { Geist, Geist_Mono, Noto_Sans_KR } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// 사용자 지시(2026-08-21): Page 1 디자인 개편 시 tvn.cjenm.com을 레퍼런스로 확인한 결과,
// 그 사이트는 Noto Sans KR을 쓴다 — Geist는 라틴 문자만 지원해 한글은 웹폰트가 전혀 적용되지
// 않고 OS 기본 한글 글꼴(Windows는 맑은 고딕 등)로 조용히 대체되고 있었다(실측: 화면 대부분이
// 한글 텍스트인데 그동안 실제로는 한 번도 웹폰트가 한글에 적용된 적이 없었음). 한글 비중이
// 절대적인 이 서비스 특성상 Noto Sans KR을 본문 글꼴로 추가한다(Geist는 영문/숫자 혼용 구간을
// 위해 유지).
const notoSansKr = Noto_Sans_KR({
  variable: "--font-noto-sans-kr",
  subsets: ["latin"],
  weight: ["400", "500", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="ko"
      className={`${geistSans.variable} ${geistMono.variable} ${notoSansKr.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
